{% set name = "titrate" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/titrate-{{ version }}.tar.gz
  sha256: 00886c3b205fda09c04ca1314f049a608d4eb71232ba7601f2886f28a7cfe816

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - numpy
    - scipy
    - matplotlib-base
    - gammapy
    - astropy
    - h5py

test:
  imports:
    - titrate
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/StFroese/TITRATE
  summary: asympTotic lIkelihood Tests for daRk mAtTer sEarch
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - StFroese
